config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"items#index"
  resources :items do
    collection do
      get 'search'
    end
    resources :item_purchases, only: [:index, :create]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :item_purchases
  has_many :comments


  validates :password, format: {with: /\A(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}\z/, message: "Include both letters and numbers" }

  with_options presence: true do
    validates :birth_date
    validates :nickname

    with_options format: { with: /\A[ぁ-んァ-ン一-龥々ー]/, message: "Full-width characters"} do
    validates :last_name
    validates :first_name
    end

    with_options format: { with: /\A[ァ-ヶー－]+\z/, message: "Full-width katakana characters"} do
    validates :last_name_kana
    validates :first_name_kana
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @items = @user.items
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="user-show">
  <div class="user-box">
    <div class="user__wrapper">
      <h2 class="name">
      <h2 class="name">
        <%= "#{@user.nickname}さんの商品"%>
      </h2>

    <ul class='user-item-lists'>
      <div class="user__card">
        <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id), method: :get do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>

          <% if item.item_purchase.present? %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %>

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.item_name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.shipping_charge.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
        <% end %>
      </div>
    </ul>
    </div>
  </div>
</div>
<%= render "shared/footer" %>